name: docker image ci

on:
  pull_request:
    branches: [ "main" ]
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            wastingnotime/contacts-frontend-react-hooks-redux #todo: uses slug
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: login on docker
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: build and push the docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}